// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EduVision.Models;
using Microsoft.EntityFrameworkCore;

namespace EduVision.DBContext;

public partial class EduVisionContext : DbContext
{
    public EduVisionContext()
    {
    }

    public EduVisionContext(DbContextOptions<EduVisionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GeneratedVideo> GeneratedVideos { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Prompt> Prompts { get; set; }

    public virtual DbSet<Quotum> Quota { get; set; }

    public virtual DbSet<Slide> Slides { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("Secrets/appsettings.Secrets.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GeneratedVideo>(entity =>
        {
            entity.HasKey(e => e.GenerateVideoId).HasName("PK__Generate__FA76872526CFFC99");

            entity.ToTable("GeneratedVideo");

            entity.Property(e => e.GenerateVideoId).HasColumnName("generateVideoID");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DurationSec).HasColumnName("duration_sec");
            entity.Property(e => e.PromptId).HasColumnName("prompt_id");
            entity.Property(e => e.Resolution)
                .HasMaxLength(50)
                .HasColumnName("resolution");
            entity.Property(e => e.SlideId).HasColumnName("slide_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.VideoUrl).HasColumnName("video_url");

            entity.HasOne(d => d.Prompt).WithMany(p => p.GeneratedVideos)
                .HasForeignKey(d => d.PromptId)
                .HasConstraintName("FK__Generated__promp__5BE2A6F2");

            entity.HasOne(d => d.Slide).WithMany(p => p.GeneratedVideos)
                .HasForeignKey(d => d.SlideId)
                .HasConstraintName("FK__Generated__slide__5CD6CB2B");
        });

        modelBuilder.Entity<Image>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__Image__336E9B757393C6E3");

            entity.ToTable("Image");

            entity.Property(e => e.ImageId).HasColumnName("imageID");
            entity.Property(e => e.Category)
                .HasMaxLength(100)
                .HasColumnName("category");
            entity.Property(e => e.Chapter)
                .HasMaxLength(100)
                .HasColumnName("chapter");
            entity.Property(e => e.Class)
                .HasMaxLength(50)
                .HasColumnName("class");
            entity.Property(e => e.Semester)
                .HasMaxLength(50)
                .HasColumnName("semester");
            entity.Property(e => e.Session)
                .HasMaxLength(50)
                .HasColumnName("session");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Url).HasColumnName("url");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Images)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Image__userID__59063A47");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__A0D9EFA6BB17A0A6");

            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId).HasColumnName("paymentID");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Payment__user_id__4CA06362");
        });

        modelBuilder.Entity<Prompt>(entity =>
        {
            entity.HasKey(e => e.Promptid).HasName("PK__Prompt__A1B260C89B284CD6");

            entity.ToTable("Prompt");

            entity.Property(e => e.Promptid).HasColumnName("promptid");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Prompts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Prompt__user_id__52593CB8");
        });

        modelBuilder.Entity<Quotum>(entity =>
        {
            entity.HasKey(e => e.QuotaId).HasName("PK__Quota__DC48C722C0DA1854");

            entity.Property(e => e.QuotaId).HasColumnName("quotaID");
            entity.Property(e => e.DailyLimit).HasColumnName("daily_limit");
            entity.Property(e => e.LastReset).HasColumnName("last_reset");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UsedWeek).HasColumnName("used_week");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Quota)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Quota__user_id__4F7CD00D");
        });

        modelBuilder.Entity<Slide>(entity =>
        {
            entity.HasKey(e => e.SlideId).HasName("PK__Slide__39AF7A8E743C398C");

            entity.ToTable("Slide");

            entity.Property(e => e.SlideId).HasColumnName("slide_id");
            entity.Property(e => e.PromptId).HasColumnName("prompt_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .HasMaxLength(100)
                .HasColumnName("type");
            entity.Property(e => e.Url).HasColumnName("url");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.Prompt).WithMany(p => p.Slides)
                .HasForeignKey(d => d.PromptId)
                .HasConstraintName("FK__Slide__prompt_id__5535A963");

            entity.HasOne(d => d.User).WithMany(p => p.Slides)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Slide__userID__5629CD9C");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__CB9A1CDF7FA65E0E");

            entity.ToTable("User");

            entity.Property(e => e.UserId).HasColumnName("userID");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Role).HasColumnName("role");
            entity.Property(e => e.UserName)
                .HasMaxLength(255)
                .HasColumnName("userName");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}