// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class Image
{
    public int ImageId { get; set; }

    public int? UserId { get; set; }

    public string Url { get; set; }

    public string Status { get; set; }

    public string Chapter { get; set; }

    public string Category { get; set; }

    public string Semester { get; set; }

    public string Session { get; set; }

    public string Class { get; set; }

    public virtual User User { get; set; }
}