// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVision.Models;

public partial class Quotum
{
    public int QuotaId { get; set; }

    public int? UserId { get; set; }

    public int? DailyLimit { get; set; }

    public int? UsedWeek { get; set; }

    public DateOnly? LastReset { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }
}